# Create mapping from server "environment" (development|test|production) to database

development:
  adapter: sqlite3
  database: db/development.sqlite3
test:
  adapter: sqlite3
  database: db/test.sqlite3
production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: db/production