# Create mapping from server "environment" (development|test|production) to database

development:
  adapter: sqlite3
  database: db/development.sqlite3
test:
  adapter: sqlite3
  database: db/test.sqlite3
production:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: db/production
  pool: 5
  username: 
  password: 